# Generated by Django 4.0.2 on 2022-02-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.TextField()),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orm.role')),
                ('Employee_name', models.CharField(max_length=50)),
                ('Employee_Email', models.CharField(max_length=50)),
                ('Employee_password', models.CharField(max_length=50)),
                ('Employee_phone', models.CharField(max_length=50)),
                ('Employee_address', models.TextField()),
                ('Employee_dob', models.DateTimeField()),
            ],
            options={
                'db_table': 'Employee',
            },
            bases=('orm.role',),
        ),
    ]
