# Generated by Django 4.0.2 on 2022-02-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
    ]
