# Generated by Django 4.0.2 on 2022-02-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer1',
            new_name='Hr',
        ),
    ]
